version: "3.2"

services:
  api:
    image: node:12.4.0-alpine
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./api:/api
    depends_on:
      - postgres
    env_file: ./api/.env
    working_dir: /api
    command: npm run start
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=quixo
      - POSTGRES_PASSWORD=quixo
      - POSTGRES_DB=quixo
    ports:
      - "5432:5432"
