version: "3.2"

services:
  postgres:
    build: docker/postgres
    environment:
      - POSTGRES_USER=quixo
      - POSTGRES_PASSWORD=quixo
      - POSTGRES_DB=quixo
    ports:
      - "5433:5432"
    expose:
      - "5433"
  advisor:
    build: docker/go
    volumes:
      - ./advisor-go/src:/go/src
    ports:
      - "8001:8001"
    expose:
      - "8001"
    command: CompileDaemon -directory="./src/quixo/" -command="./src/quixo/quixo"
  api:
    image: node:12.4.0-stretch
    ports:
      - "3001:3001"
    expose:
      - "3001"
    volumes:
      - ./api:/api
      - ./docker/wait-for-it.sh:/docker/wait-for-it.sh
    depends_on:
      - postgres
      - advisor
    env_file: ./api/.env
    working_dir: /api
    command:
      ["/docker/wait-for-it.sh", "postgres:5433", "--", "npm", "run", "start"]
    restart: always
    network_mode: host
